added db ping check on interval basis
h-tendy/datagroom-gateway pull request #34
Opened 2023-08-22 14:06 UTC by infinan12

2023-08-24 16:35 UTC, hrishi2710 approved these changes

2023-08-24 16:55 UTC, hrishi2710 commented on server.js
> +var connectedClient;
We have to maintain an array of client here to send the dbConnectivity state to all of them periodically.

2023-08-24 16:56 UTC, hrishi2710 requested changes
Needs work on the comment.

2023-09-04 04:47 UTC, hrishi2710 approved these changes

2023-09-04 05:19 UTC, h-tendy commented on server.js
> +        db.destroy();
Please add an `await` here.

2023-09-04 06:09 UTC, h-tendy approved these changes

2023-09-04 06:09 UTC, merged